### ISSUE TITLE
Failed to compile: function strptime() not defined (solved)

### ISSUE THREAD

**Issue by RoSchmi** [vquelque/ESP32ConsoFioul#1]
Thank you for posting your code,
got it basically running now but first had an issue with the function 'strptime()' in your method 'void loadLastCounterFromThingsSpeak()' 
as the code didn't compile. 

![strptime_issue](https://user-images.githubusercontent.com/24595510/140104851-2804adcd-d442-4bb4-9711-16dada05110b.png)

Finally I found a solution here: https://community.platformio.org/t/identifier-is-undefined-setenv-tzset/16162.
It compiled after I copied from <time.h>

char      *_EXFUN(strptime,     (const char *__restrict,
				 const char *__restrict,
				 struct tm *__restrict));
_VOID      _EXFUN(tzset,	(_VOID));
_VOID      _EXFUN(_tzset_r,	(struct _reent *));

right after the #include statements to the top of the sketch.

Surprisingly, after it had compiled one time, it compiled even when this part was commented out.
Only wanted to post this here, for the case that eventually someone else would have the same problem.
Btw: Perhaps you are interested in my solution for monitoring the heating burner by using a microphone:
https://github.com/RoSchmi/Esp32_WiFiManager_HeatingSurvey

**Comment by vquelque** [comment]
HI @RoSchmi  ! 
Many thanks for your comment and for the fix. Glad you managed to make it working :).
